# Generated by Django 5.2.7 on 2026-01-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_verificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave',
            new_name='password',
        ),
    ]
