# Generated by Django 5.2.7 on 2026-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_clave_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='verificacion',
            field=models.CharField(max_length=100),
        ),
    ]
